name: "Build and Test"

on: 
  push:
    paths:
      - 'src/*'
      - 'docs/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install packages
      run: npm ci
    - name: Build the project
      run: npm run build
    - name: Run linter
      run: npm run lint
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pattern: '*.ts'
