name: "Build and Test"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install packages
      run: npm ci
    - name: Build the project
      run: npm run build
    - name: Run linterLint
      uses: mooyoul/tslint-actions@v1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pattern: '*.ts'
