name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v1
      - name: Install packages
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Add _auth to .npmrc
        run: npm config set //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
      - name: Publish to NPM
        run: npm run publish:lib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
